### PR TITLE
Fix error "Cannot read property 'translatedText' of undefined" in case of translating a single term

### PR DESCRIPTION
**Pull request by mqamhieh**
Task fails in case of translating only one term (sentence)

### CODE REVIEW

**Comment by dolanmiu** [comment]
I am reviewing the pull request now.

Thank you!

`translations` should be an array so it should be `translations[i].translatedText;` and not be `translations.translatedText;`

However I do see what you mean, it would be nice to have it support single `translatedText` without having to declare an array...

Can you send me your grunt configuration for this plugin, so I have a better idea?

**Comment by qamhiehharri** [comment]
Here is my Gruntfile configuration for google_translate task:

```
default_options: {
            options: {
                googleApiKey: '************************************'
            },
            files: [{
                src: '.tmp/i18n/en.json',
                sourceLanguage: 'en',
                targetLanguages: ['es'],
                dest: '.tmp/i18n/'
            }]
        }
```

The issue appears when en.json is:

```
{
    "Collection of personally identifiable information": "Collection of personally identifiable information"
}
```

google_translate task fails with this in console:

```
Running "google_translate:default_options" (google_translate) task
Translating into: es
Fatal error: Cannot read property 'translatedText' of undefined
```

This is because when you send a single term in `q` parameter to Google Translate API, the response is an object instead of array.

**Comment by dolanmiu** [comment]
Oh I see.

I was not aware of this edge-case.

Will merge in promptly

I will update the npm package tonight after work.

**Comment by dolanmiu** [comment]
Done. It is now published on NPM as version `1.0.3`

**Comment by qamhiehharri** [comment]
Thanks.

**Pull request merged**
